using Godot;
using BreakInfinity;
using System;
using System.Collections.Generic;

public partial class Resources : Node
{
    /// <summary>
    /// Dictionary containing the amount of each resource in the game. The key is the resource name, and the value is the amount of that resource.
    /// </summary>
    private Dictionary<string, double> _resourcesWood = new Dictionary<string, double>()
    {
    // LOW
    { "Douglas Fir", 0 },
    { "Scandinavian Redwood", 0 },
    { "Southern Yellow Pine", 0 },
    { "Tulipwood (Poplar)", 0 },

    // MEDIUM
    { "Akossika", 0 },
    { "Alone", 0 },
    { "American Hornbeam", 0 },
    { "Amunu", 0 },
    { "Angelica Tree", 0 },
    { "Angico", 0 },
    { "Aningeria", 0 },
    { "Antarctic Beech", 0 },
    { "Antiaris", 0 },
    { "Araiba", 0 },
    { "Araracanga", 0 },
    { "Arkensas Oak", 0 },
    { "Ash (American White)", 0 },
    { "Ashe Juniper", 0 },
    { "Australian White Birch", 0 },
    { "Balsamo", 0 },
    { "Beech (Euro)", 0 },
    { "Beli", 0 },
    { "Berlinia", 0 },
    { "Black Spruce", 0 },
    { "Black Wattle", 0 },
    { "Blackheart Sassafras", 0 },
    { "Blue Gum", 0 },
    { "Blue Mahoe", 0 },
    { "Bolly Silkwood", 0 },
    { "Bombanga", 0 },
    { "Brazilnut", 0 },
    { "Breadtree", 0 },
    { "Bridgalow", 0 },
    { "Bristlecone Pine", 0 },
    { "Brown Quangdong", 0 },
    { "Brown Sterculia", 0 },
    { "Calantas", 0 },
    { "Californian Red Fir", 0 },
    { "Camphor Laurel", 0 },
    { "Cananga", 0 },
    { "Canarywood", 0 },
    { "Cangerana", 0 },
    { "Capa De Tabaco", 0 },
    { "Capomo", 0 },
    { "Carbbean Pine", 0 },
    { "Carbonero", 0 },
    { "Carne D'Anta", 0 },
    { "Cedar Elm", 0 },
    { "Chechem", 0 },
    { "Chewstick", 0 },
    { "Coconut", 0 },
    { "Cocuswood", 0 },
    { "Coigue", 0 },
    { "Copaiba", 0 },
    { "Cow Tree", 0 },
    { "Crabwood (Andiroba)", 0 },
    { "Cucumber Tree", 0 },
    { "Curupay", 0 },
    { "Dahoma", 0 },
    { "Danta", 0 },
    { "Dark Red Meranti", 0 },
    { "Duru", 0 },
    { "East African Comphorwood", 0 },
    { "Ebano", 0 },
    { "Esia", 0 },
    { "Espave", 0 },
    { "Forest Oak", 0 },
    { "Fustic", 0 },
    { "Genero Lemonwood", 0 },
    { "Giant Chinkapin", 0 },
    { "Giant Sequoia", 0 },
    { "Gidgee", 0 },
    { "Ginkgo", 0 },
    { "Grandis, Red", 0 },
    { "Grumixava", 0 },
    { "Haiari", 0 },
    { "Hemlock Western", 0 },
    { "Hoeboe", 0 },
    { "Hura Possumwood", 0 },
    { "Idigbo", 0 },
    { "Indian Almond", 0 },
    { "Indian Silver Greywood", 0 },
    { "Izombe", 0 },
    { "Jaboty", 0 },
    { "Jagua", 0 },
    { "Japanese Beech", 0 },
    { "Japanese Birch", 0 },
    { "Japanese Fir", 0 },
    { "Japanese Hemlock", 0 },
    { "Japanese Red Pine", 0 },
    { "Japanese Spruce", 0 },
    { "Jucaro", 0 },
    { "Kaatoan Bangkal", 0 },
    { "Kahikatea", 0 },
    { "Kaki", 0 },
    { "Katsura", 0 },
    { "Kauvula", 0 },
    { "Kirikawa (Marakaipo)", 0 },
    { "Lampati", 0 },
    { "Lancewood", 0 },
    { "Larch (European)", 0 },
    { "Lauro Preto", 0 },
    { "Leche Perra", 0 },
    { "Live Oak", 0 },
    { "Long John", 0 },
    { "Mango", 0 },
    { "Mangrove", 0 },
    { "Manwood", 0 },
    { "Morototo", 0 },
    { "Muhimbi", 0 },
    { "Mulga", 0 },
    { "Mutenye", 0 },
    { "Nargusta", 0 },
    { "New Guinea Boxwood", 0 },
    { "Niangon", 0 },
    { "Northern Catalpa", 0 },
    { "Northern Sassafras", 0 },
    { "Obota", 0 },
    { "Odoko", 0 },
    { "Ogea", 0 },
    { "Okwen", 0 },
    { "Oysterwood", 0 },
    { "Pau Amarello", 0 },
    { "Pawpap", 0 },
    { "Pine (Radiata)", 0 },
    { "Piqui", 0 },
    { "Pochote", 0 },
    { "Podo", 0 },
    { "Poplar Gum", 0 },
    { "Rauli", 0 },
    { "Red Chacate", 0 },
    { "Red Siris", 0 },
    { "Red Spruce", 0 },
    { "Red Tulip Oak", 0 },
    { "Rengas", 0 },
    { "Rose Alder", 0 },
    { "Rubbertree (Rubberwood)", 0 },
    { "Sajo", 0 },
    { "Sapele", 0 },
    { "Sapodilla", 0 },
    { "Satine", 0 },
    { "Scarlet Oak", 0 },
    { "Sen", 0 },
    { "Sepetir", 0 },
    { "Serrette", 0 },
    { "Siberian Yellow Pine", 0 },
    { "Smooth-Leaved Elm", 0 },
    { "Sophora", 0 },
    { "Spruce", 0 },
    { "Steamed Beech", 0 },
    { "Subalpine Fir", 0 },
    { "Sugi", 0 },
    { "Swamp White Oak", 0 },
    { "Sweet Birch", 0 },
    { "Sycamore", 0 },
    { "Table Mountain Pine", 0 },
    { "Tamarind", 0 },
    { "Taun", 0 },
    { "Tawa", 0 },
    { "Tchitola", 0 },
    { "Tea Tree", 0 },
    { "Timbauba", 0 },
    { "Trumpetwood", 0 },
    { "Verawood", 0 },
    { "Wacapou", 0 },
    { "Water Gum", 0 },
    { "Water Tupelo", 0 },
    { "West African Cordia", 0 },
    { "White Cypress Pine", 0 },
    { "White Hazelwood", 0 },
    { "White Quangdong", 0 },
    { "White-Topped Box", 0 },
    { "Yellow Sanders", 0 },
    { "Yellow Siris", 0 },

    // HIGH
    { "Alder (European)", 0 },
    { "Alder (Red)", 0 },
    { "American Red Oak", 0 },
    { "Apple", 0 },
    { "Ash (European)", 0 },
    { "Ayan", 0 },
    { "Balsa", 0 },
    { "Birch (European)", 0 },
    { "Birch (Yellow)", 0 },
    { "Cedar", 0 },
    { "Cherry", 0 },
    { "Cherry (European)", 0 },
    { "Chestnut (Sweet)", 0 },
    { "Elm (American)", 0 },
    { "Elm (English)", 0 },
    { "Elm European", 0 },
    { "Green Oak", 0 },
    { "Hickory", 0 },
    { "Holly", 0 },
    { "Iroko", 0 },
    { "Lime, European", 0 },
    { "Majau", 0 },
    { "Maple (American)", 0 },
    { "Oak - Joinery Grade S/E (Euro)", 0 },
    { "Oak - Prime S/E (Euro)", 0 },
    { "Obeche", 0 },
    { "Pine (Eastern White)", 0 },
    { "Pine (Lodgepole)", 0 },
    { "Pine (Longleaf And Slash)", 0 },
    { "Pine (Ponderosa)", 0 },
    { "Pine (Sugar)", 0 },
    { "Pine (Western White)", 0 },
    { "Pine - Parana Pine", 0 },
    { "Purpleheart", 0 },
    { "Seasoned Oak", 0 },
    { "Spruce (Sitka)", 0 },
    { "Sycamore (European)", 0 },
    { "Utile", 0 },
    { "Willow", 0 },
    { "Yew (European)", 0 },
    { "Australian White Ash", 0 },
    { "Light American Corda", 0 },
    { "Nyatoh", 0 },
    { "Oregon White Oak", 0 },
    { "Paldao", 0 },
    { "Palo Santo", 0 },
    { "Red Lancewood", 0 },
    { "Spanish Cedar", 0 },

    // EXPENSIVE
    { "Accoya", 0 },
    { "Afromosia", 0 },
    { "Amboyna", 0 },
    { "Anigre", 0 },
    { "Aspen (Canadian)", 0 },
    { "Basswood", 0 },
    { "Black Walnut (American)", 0 },
    { "Blackbean", 0 },
    { "Boxwood (European)", 0 },
    { "Cedar (Port Orford)", 0 },
    { "Cedar (Southern White)", 0 },
    { "Cedro", 0 },
    { "Ceylon Satinwood", 0 },
    { "Chestnut (American)", 0 },
    { "Chestnut (Horse)", 0 },
    { "Coachwood", 0 },
    { "Cumaru", 0 },
    { "Degame", 0 },
    { "Dogwood", 0 },
    { "Freijo", 0 },
    { "Hackberry", 0 },
    { "Imbuia", 0 },
    { "Ipe", 0 },
    { "Jelutong", 0 },
    { "Kapur", 0 },
    { "Koa", 0 },
    { "Lati", 0 },
    { "Light Virola", 0 },
    { "Magnolia", 0 },
    { "Mansonia", 0 },
    { "Merbau", 0 },
    { "Mesquite", 0 },
    { "Muhuhu", 0 },
    { "Muninga", 0 },
    { "Myrtle", 0 },
    { "Oak (American White)", 0 },
    { "Oak - Character Grade (Euro)", 0 },
    { "Olive (East African)", 0 },
    { "Olive (European)", 0 },
    { "Opepe", 0 },
    { "Padauk - African", 0 },
    { "Paduak", 0 },
    { "Panga Panga", 0 },
    { "Paulownia", 0 },
    { "Pear", 0 },
    { "Pecan", 0 },
    { "Pine (Hoop)", 0 },
    { "Pine (Kauri)", 0 },
    { "Primavera", 0 },
    { "Quebracho", 0 },
    { "Ramin", 0 },
    { "Robinia", 0 },
    { "Sassafras", 0 },
    { "Sequoia (Redwood)", 0 },
    { "Snakewood", 0 },
    { "Sucupira", 0 },
    { "Thermowood", 0 },
    { "Yellow Buckeye", 0 },
    { "Ziricote", 0 },
    { "Acajou Rouge", 0 },
    { "Amendoim", 0 },
    { "Bishopwood", 0 },
    { "Brush Box", 0 },
    { "Cativo", 0 },
    { "East Indian Kauri", 0 },
    { "Fitzroy Cypress", 0 },
    { "Flamewood", 0 },
    { "Jequitiba", 0 },
    { "Kempas", 0 },
    { "Keyaki", 0 },
    { "Marblewood", 0 },
    { "Moabi", 0 },
    { "Omu", 0 },
    { "Tonka", 0 },
    { "Ulmo", 0 },
    { "Yellow Carabeen", 0 },

    // VERY EXPENSIVE
    { "Abura", 0 },
    { "Afara", 0 },
    { "Afzelia", 0 },
    { "Agba", 0 },
    { "Angelin", 0 },
    { "Avodire", 0 },
    { "Balau", 0 },
    { "Blackwood (African)", 0 },
    { "Blackwood (Australian)", 0 },
    { "Brazilwood", 0 },
    { "Bubinga", 0 },
    { "Cerejeira", 0 },
    { "Cocobolo", 0 },
    { "Courbaril", 0 },
    { "Ebony (African)", 0 },
    { "Ebony (Macassar)", 0 },
    { "Ekki", 0 },
    { "Gaboon", 0 },
    { "Gedu Nohor", 0 },
    { "Goncalo Alves", 0 },
    { "Greenheart", 0 },
    { "Guanacaste", 0 },
    { "Guarea", 0 },
    { "Jacaranda Pardo", 0 },
    { "Jacareuba", 0 },
    { "Jarrah", 0 },
    { "Karri", 0 },
    { "Keruing", 0 },
    { "Kingwood", 0 },
    { "Kokko", 0 },
    { "Koto", 0 },
    { "Laburnum", 0 },
    { "Lignum Vitae", 0 },
    { "Madrona", 0 },
    { "Mahogany (American)", 0 },
    { "Mahogany - African", 0 },
    { "Makore", 0 },
    { "Maracaibo Boxwood", 0 },
    { "Massaranduba", 0 },
    { "Mengkulang", 0 },
    { "Mersawa", 0 },
    { "Okan", 0 },
    { "Osage-Orange", 0 },
    { "Ovangkol", 0 },
    { "Padauk (Burma)", 0 },
    { "Pau Marfim", 0 },
    { "Peroba Rosa", 0 },
    { "Persimmon", 0 },
    { "Rosewood (Brazilian)", 0 },
    { "Rosewood (Honduras)", 0 },
    { "Rosewood (Indian)", 0 },
    { "Sheoak", 0 },
    { "Tallowwood", 0 },
    { "Tatajuba", 0 },
    { "Teak", 0 },
    { "Teak (Rhodesian)", 0 },
    { "Walnut (African)", 0 },
    { "Wenge", 0 },
    { "Zebrano", 0 },
    { "Etimoe", 0 },
    { "Gabon Ebony", 0 },
    { "Miva Mahogany", 0 },
    { "Sandalwood", 0 },
    { "South American Walnut", 0 },
    { "Totara", 0 },
    { "Vanuatu Blackwood", 0 },
    };
    /// <summary>
    ///  Dictionary containing the cost of crafting planks from resources. The key is the resource name, and the value is the cost in terms of some currency or points.
    /// </summary>
    private Dictionary<string, double> _resourcesPlanks = new Dictionary<string, double>()
    {
    // LOW
    { "Douglas Fir Planks", 0 },
    { "Scandinavian Redwood Planks", 0 },
    { "Southern Yellow Pine Planks", 0 },
    { "Tulipwood (Poplar) Planks", 0 },

    // MEDIUM
    { "Akossika Planks", 0 },
    { "Alone Planks", 0 },
    { "American Hornbeam Planks", 0 },
    { "Amunu Planks", 0 },
    { "Angelica Tree Planks", 0 },
    { "Angico Planks", 0 },
    { "Aningeria Planks", 0 },
    { "Antarctic Beech Planks", 0 },
    { "Antiaris Planks", 0 },
    { "Araiba Planks", 0 },
    { "Araracanga Planks", 0 },
    { "Arkensas Oak Planks", 0 },
    { "Ash (American White) Planks", 0 },
    { "Ashe Juniper Planks", 0 },
    { "Australian White Birch Planks", 0 },
    { "Balsamo Planks", 0 },
    { "Beech (Euro) Planks", 0 },
    { "Beli Planks", 0 },
    { "Berlinia Planks", 0 },
    { "Black Spruce Planks", 0 },
    { "Black Wattle Planks", 0 },
    { "Blackheart Sassafras Planks", 0 },
    { "Blue Gum Planks", 0 },
    { "Blue Mahoe Planks", 0 },
    { "Bolly Silkwood Planks", 0 },
    { "Bombanga Planks", 0 },
    { "Brazilnut Planks", 0 },
    { "Breadtree Planks", 0 },
    { "Bridgalow Planks", 0 },
    { "Bristlecone Pine Planks", 0 },
    { "Brown Quangdong Planks", 0 },
    { "Brown Sterculia Planks", 0 },
    { "Calantas Planks", 0 },
    { "Californian Red Fir Planks", 0 },
    { "Camphor Laurel Planks", 0 },
    { "Cananga Planks", 0 },
    { "Canarywood Planks", 0 },
    { "Cangerana Planks", 0 },
    { "Capa De Tabaco Planks", 0 },
    { "Capomo Planks", 0 },
    { "Carbbean Pine Planks", 0 },
    { "Carbonero Planks", 0 },
    { "Carne D'Anta Planks", 0 },
    { "Cedar Elm Planks", 0 },
    { "Chechem Planks", 0 },
    { "Chewstick Planks", 0 },
    { "Coconut Planks", 0 },
    { "Cocuswood Planks", 0 },
    { "Coigue Planks", 0 },
    { "Copaiba Planks", 0 },
    { "Cow Tree Planks", 0 },
    { "Crabwood (Andiroba) Planks", 0 },
    { "Cucumber Tree Planks", 0 },
    { "Curupay Planks", 0 },
    { "Dahoma Planks", 0 },
    { "Danta Planks", 0 },
    { "Dark Red Meranti Planks", 0 },
    { "Duru Planks", 0 },
    { "East African Comphorwood Planks", 0 },
    { "Ebano Planks", 0 },
    { "Esia Planks", 0 },
    { "Espave Planks", 0 },
    { "Forest Oak Planks", 0 },
    { "Fustic Planks", 0 },
    { "Genero Lemonwood Planks", 0 },
    { "Giant Chinkapin Planks", 0 },
    { "Giant Sequoia Planks", 0 },
    { "Gidgee Planks", 0 },
    { "Ginkgo Planks", 0 },
    { "Grandis, Red Planks", 0 },
    { "Grumixava Planks", 0 },
    { "Haiari Planks", 0 },
    { "Hemlock Western Planks", 0 },
    { "Hoeboe Planks", 0 },
    { "Hura Possumwood Planks", 0 },
    { "Idigbo Planks", 0 },
    { "Indian Almond Planks", 0 },
    { "Indian Silver Greywood Planks", 0 },
    { "Izombe Planks", 0 },
    { "Jaboty Planks", 0 },
    { "Jagua Planks", 0 },
    { "Japanese Beech Planks", 0 },
    { "Japanese Birch Planks", 0 },
    { "Japanese Fir Planks", 0 },
    { "Japanese Hemlock Planks", 0 },
    { "Japanese Red Pine Planks", 0 },
    { "Japanese Spruce Planks", 0 },
    { "Jucaro Planks", 0 },
    { "Kaatoan Bangkal Planks", 0 },
    { "Kahikatea Planks", 0 },
    { "Kaki Planks", 0 },
    { "Katsura Planks", 0 },
    { "Kauvula Planks", 0 },
    { "Kirikawa (Marakaipo) Planks", 0 },
    { "Lampati Planks", 0 },
    { "Lancewood Planks", 0 },
    { "Larch (European) Planks", 0 },
    { "Lauro Preto Planks", 0 },
    { "Leche Perra Planks", 0 },
    { "Live Oak Planks", 0 },
    { "Long John Planks", 0 },
    { "Mango Planks", 0 },
    { "Mangrove Planks", 0 },
    { "Manwood Planks", 0 },
    { "Morototo Planks", 0 },
    { "Muhimbi Planks", 0 },
    { "Mulga Planks", 0 },
    { "Mutenye Planks", 0 },
    { "Nargusta Planks", 0 },
    { "New Guinea Boxwood Planks", 0 },
    { "Niangon Planks", 0 },
    { "Northern Catalpa Planks", 0 },
    { "Northern Sassafras Planks", 0 },
    { "Obota Planks", 0 },
    { "Odoko Planks", 0 },
    { "Ogea Planks", 0 },
    { "Okwen Planks", 0 },
    { "Oysterwood Planks", 0 },
    { "Pau Amarello Planks", 0 },
    { "Pawpap Planks", 0 },
    { "Pine (Radiata) Planks", 0 },
    { "Piqui Planks", 0 },
    { "Pochote Planks", 0 },
    { "Podo Planks", 0 },
    { "Poplar Gum Planks", 0 },
    { "Rauli Planks", 0 },
    { "Red Chacate Planks", 0 },
    { "Red Siris Planks", 0 },
    { "Red Spruce Planks", 0 },
    { "Red Tulip Oak Planks", 0 },
    { "Rengas Planks", 0 },
    { "Rose Alder Planks", 0 },
    { "Rubbertree (Rubberwood) Planks", 0 },
    { "Sajo Planks", 0 },
    { "Sapele Planks", 0 },
    { "Sapodilla Planks", 0 },
    { "Satine Planks", 0 },
    { "Scarlet Oak Planks", 0 },
    { "Sen Planks", 0 },
    { "Sepetir Planks", 0 },
    { "Serrette Planks", 0 },
    { "Siberian Yellow Pine Planks", 0 },
    { "Smooth-Leaved Elm Planks", 0 },
    { "Sophora Planks", 0 },
    { "Spruce Planks", 0 },
    { "Steamed Beech Planks", 0 },
    { "Subalpine Fir Planks", 0 },
    { "Sugi Planks", 0 },
    { "Swamp White Oak Planks", 0 },
    { "Sweet Birch Planks", 0 },
    { "Sycamore Planks", 0 },
    { "Table Mountain Pine Planks", 0 },
    { "Tamarind Planks", 0 },
    { "Taun Planks", 0 },
    { "Tawa Planks", 0 },
    { "Tchitola Planks", 0 },
    { "Tea Tree Planks", 0 },
    { "Timbauba Planks", 0 },
    { "Trumpetwood Planks", 0 },
    { "Verawood Planks", 0 },
    { "Wacapou Planks", 0 },
    { "Water Gum Planks", 0 },
    { "Water Tupelo Planks", 0 },
    { "West African Cordia Planks", 0 },
    { "White Cypress Pine Planks", 0 },
    { "White Hazelwood Planks", 0 },
    { "White Quangdong Planks", 0 },
    { "White-Topped Box Planks", 0 },
    { "Yellow Sanders Planks", 0 },
    { "Yellow Siris Planks", 0 },

    // HIGH
    { "Alder (European) Planks", 0 },
    { "Alder (Red) Planks", 0 },
    { "American Red Oak Planks", 0 },
    { "Apple Planks", 0 },
    { "Ash (European) Planks", 0 },
    { "Ayan Planks", 0 },
    { "Balsa Planks", 0 },
    { "Birch (European) Planks", 0 },
    { "Birch (Yellow) Planks", 0 },
    { "Cedar Planks", 0 },
    { "Cherry Planks", 0 },
    { "Cherry (European) Planks", 0 },
    { "Chestnut (Sweet) Planks", 0 },
    { "Elm (American) Planks", 0 },
    { "Elm (English) Planks", 0 },
    { "Elm European Planks", 0 },
    { "Green Oak Planks", 0 },
    { "Hickory Planks", 0 },
    { "Holly Planks", 0 },
    { "Iroko Planks", 0 },
    { "Lime, European Planks", 0 },
    { "Majau Planks", 0 },
    { "Maple (American) Planks", 0 },
    { "Oak - Joinery Grade S/E (Euro)", 0 },
    { "Oak - Prime S/E (Euro)", 0 },
    { "Obeche Planks", 0 },
    { "Pine (Eastern White) Planks", 0 },
    { "Pine (Lodgepole) Planks", 0 },
    { "Pine (Longleaf And Slash) Planks", 0 },
    { "Pine (Ponderosa) Planks", 0 },
    { "Pine (Sugar) Planks", 0 },
    { "Pine (Western White) Planks", 0 },
    { "Pine - Parana Pine Planks", 0 },
    { "Purpleheart Planks", 0 },
    { "Seasoned Oak Planks", 0 },
    { "Spruce (Sitka) Planks", 0 },
    { "Sycamore (European) Planks", 0 },
    { "Utile Planks", 0 },
    { "Willow Planks", 0 },
    { "Yew (European) Planks", 0 },
    { "Australian White Ash Planks", 0 },
    { "Light American Corda Planks", 0 },
    { "Nyatoh Planks", 0 },
    { "Oregon White Oak Planks", 0 },
    { "Paldao Planks", 0 },
    { "Palo Santo Planks", 0 },
    { "Red Lancewood Planks", 0 },
    { "Spanish Cedar Planks", 0 },

    // EXPENSIVE
    { "Accoya Planks", 0 },
    { "Afromosia Planks", 0 },
    { "Amboyna Planks", 0 },
    { "Anigre Planks", 0 },
    { "Aspen (Canadian) Planks", 0 },
    { "Basswood Planks", 0 },
    { "Black Walnut (American) Planks", 0 },
    { "Blackbean Planks", 0 },
    { "Boxwood (European) Planks", 0 },
    { "Cedar (Port Orford) Planks", 0 },
    { "Cedar (Southern White) Planks", 0 },
    { "Cedro Planks", 0 },
    { "Ceylon Satinwood Planks", 0 },
    { "Chestnut (American) Planks", 0 },
    { "Chestnut (Horse) Planks", 0 },
    { "Coachwood Planks", 0 },
    { "Cumaru Planks", 0 },
    { "Degame Planks", 0 },
    { "Dogwood Planks", 0 },
    { "Freijo Planks", 0 },
    { "Hackberry Planks", 0 },
    { "Imbuia Planks", 0 },
    { "Ipe Planks", 0 },
    { "Jelutong Planks", 0 },
    { "Kapur Planks", 0 },
    { "Koa Planks", 0 },
    { "Lati Planks", 0 },
    { "Light Virola Planks", 0 },
    { "Magnolia Planks", 0 },
    { "Mansonia Planks", 0 },
    { "Merbau Planks", 0 },
    { "Mesquite Planks", 0 },
    { "Muhuhu Planks", 0 },
    { "Muninga Planks", 0 },
    { "Myrtle Planks", 0 },
    { "Oak (American White) Planks", 0 },
    { "Oak - Character Grade (Euro)", 0 },
    { "Olive (East African) Planks", 0 },
    { "Olive (European) Planks", 0 },
    { "Opepe Planks", 0 },
    { "Padauk - African Planks", 0 },
    { "Paduak Planks", 0 },
    { "Panga Panga Planks", 0 },
    { "Paulownia Planks", 0 },
    { "Pear Planks", 0 },
    { "Pecan Planks", 0 },
    { "Pine (Hoop) Planks", 0 },
    { "Pine (Kauri) Planks", 0 },
    { "Primavera Planks", 0 },
    { "Quebracho Planks", 0 },
    { "Ramin Planks", 0 },
    { "Robinia Planks", 0 },
    { "Sassafras Planks", 0 },
    { "Sequoia (Redwood) Planks", 0 },
    { "Snakewood Planks", 0 },
    { "Sucupira Planks", 0 },
    { "Thermowood Planks", 0 },
    { "Yellow Buckeye Planks", 0 },
    { "Ziricote Planks", 0 },
    { "Acajou Rouge Planks", 0 },
    { "Amendoim Planks", 0 },
    { "Bishopwood Planks", 0 },
    { "Brush Box Planks", 0 },
    { "Cativo Planks", 0 },
    { "East Indian Kauri Planks", 0 },
    { "Fitzroy Cypress Planks", 0 },
    { "Flamewood Planks", 0 },
    { "Jequitiba Planks", 0 },
    { "Kempas Planks", 0 },
    { "Keyaki Planks", 0 },
    { "Marblewood Planks", 0 },
    { "Moabi Planks", 0 },
    { "Omu Planks", 0 },
    { "Tonka Planks", 0 },
    { "Ulmo Planks", 0 },
    { "Yellow Carabeen Planks", 0 },

    // VERY EXPENSIVE
    { "Abura", 0 },
    { "Afara", 0 },
    { "Afzelia", 0 },
    { "Agba", 0 },
    { "Angelin", 0 },
    { "Avodire", 0 },
    { "Balau", 0 },
    { "Blackwood (African)", 0 },
    { "Blackwood (Australian)", 0 },
    { "Brazilwood", 0 },
    { "Bubinga", 0 },
    { "Cerejeira", 0 },
    { "Cocobolo", 0 },
    { "Courbaril", 0 },
    { "Ebony (African)", 0 },
    { "Ebony (Macassar)", 0 },
    { "Ekki", 0 },
    { "Gaboon", 0 },
    { "Gedu Nohor", 0 },
    { "Goncalo Alves", 0 },
    { "Greenheart", 0 },
    { "Guanacaste", 0 },
    { "Guarea", 0 },
    { "Jacaranda Pardo", 0 },
    { "Jacareuba", 0 },
    { "Jarrah", 0 },
    { "Karri", 0 },
    { "Keruing", 0 },
    { "Kingwood", 0 },
    { "Kokko", 0 },
    { "Koto", 0 },
    { "Laburnum", 0 },
    { "Lignum Vitae", 0 },
    { "Madrona", 0 },
    { "Mahogany (American)", 0 },
    { "Mahogany - African", 0 },
    { "Makore", 0 },
    { "Maracaibo Boxwood", 0 },
    { "Massaranduba", 0 },
    { "Mengkulang", 0 },
    { "Mersawa", 0 },
    { "Okan", 0 },
    { "Osage-Orange", 0 },
    { "Ovangkol", 0 },
    { "Padauk (Burma)", 0 },
    { "Pau Marfim", 0 },
    { "Peroba Rosa", 0 },
    { "Persimmon", 0 },
    { "Rosewood (Brazilian)", 0 },
    { "Rosewood (Honduras)", 0 },
    { "Rosewood (Indian)", 0 },
    { "Sheoak", 0 },
    { "Tallowwood", 0 },
    { "Tatajuba", 0 },
    { "Teak", 0 },
    { "Teak (Rhodesian)", 0 },
    { "Walnut (African)", 0 },
    { "Wenge", 0 },
    { "Zebrano", 0 },
    { "Etimoe", 0 },
    { "Gabon Ebony", 0 },
    { "Miva Mahogany", 0 },
    { "Sandalwood", 0 },
    { "South American Walnut", 0 },
    { "Totara", 0 },
    { "Vanuatu Blackwood", 0 },
    };

    /// <summary>
    /// Dictionary containing the cost of crafting planks from resources. The key is the resource name, and the value is the cost in terms of some currency or points.
    /// </summary>
    private Dictionary<string, double> _resourcesPlankCraftCost = new Dictionary<string, double>()
    {
    // LOW
    { "Douglas Fir Planks", 1 },
    { "Scandinavian Redwood Planks", 2 },
    { "Southern Yellow Pine Planks", 3 },
    { "Tulipwood (Poplar) Planks", 4 },

    // MEDIUM
    { "Akossika Planks", 5 },
    { "Alone Planks", 6 },
    { "American Hornbeam Planks", 7 },
    { "Amunu Planks", 8 },
    { "Angelica Tree Planks", 9 },
    { "Angico Planks", 10 },
    { "Aningeria Planks", 11 },
    { "Antarctic Beech Planks", 12 },
    { "Antiaris Planks", 13 },
    { "Araiba Planks", 14 },
    { "Araracanga Planks", 15 },
    { "Arkensas Oak Planks", 16 },
    { "Ash (American White) Planks", 17 },
    { "Ashe Juniper Planks", 18 },
    { "Australian White Birch Planks", 19 },
    { "Balsamo Planks", 20 },
    { "Beech (Euro) Planks", 21 },
    { "Beli Planks", 22 },
    { "Berlinia Planks", 23 },
    { "Black Spruce Planks", 24 },
    { "Black Wattle Planks", 25 },
    { "Blackheart Sassafras Planks", 26 },
    { "Blue Gum Planks", 27 },
    { "Blue Mahoe Planks", 28 },
    { "Bolly Silkwood Planks", 29 },
    { "Bombanga Planks", 30 },
    { "Brazilnut Planks", 31 },
    { "Breadtree Planks", 32 },
    { "Bridgalow Planks", 33 },
    { "Bristlecone Pine Planks", 34 },
    { "Brown Quangdong Planks", 35 },
    { "Brown Sterculia Planks", 36 },
    { "Calantas Planks", 37 },
    { "Californian Red Fir Planks", 38 },
    { "Camphor Laurel Planks", 39 },
    { "Cananga Planks", 40 },
    { "Canarywood Planks", 41 },
    { "Cangerana Planks", 42 },
    { "Capa De Tabaco Planks", 43 },
    { "Capomo Planks", 44 },
    { "Carbbean Pine Planks", 45 },
    { "Carbonero Planks", 46 },
    { "Carne D'Anta Planks", 47 },
    { "Cedar Elm Planks", 48 },
    { "Chechem Planks", 49 },
    { "Chewstick Planks", 50 },
    { "Coconut Planks", 51 },
    { "Cocuswood Planks", 52 },
    { "Coigue Planks", 53 },
    { "Copaiba Planks", 54 },
    { "Cow Tree Planks", 55 },
    { "Crabwood (Andiroba) Planks", 56 },
    { "Cucumber Tree Planks", 57 },
    { "Curupay Planks", 58 },
    { "Dahoma Planks", 59 },
    { "Danta Planks", 60 },
    { "Dark Red Meranti Planks", 61 },
    { "Duru Planks", 62 },
    { "East African Comphorwood Planks", 63 },
    { "Ebano Planks", 64 },
    { "Esia Planks", 65 },
    { "Espave Planks", 66 },
    { "Forest Oak Planks", 67 },
    { "Fustic Planks", 68 },
    { "Genero Lemonwood Planks", 69 },
    { "Giant Chinkapin Planks", 70 },
    { "Giant Sequoia Planks", 71 },
    { "Gidgee Planks", 72 },
    { "Ginkgo Planks", 73 },
    { "Grandis, Red Planks", 74 },
    { "Grumixava Planks", 75 },
    { "Haiari Planks", 76 },
    { "Hemlock Western Planks", 77 },
    { "Hoeboe Planks", 78 },
    { "Hura Possumwood Planks", 79 },
    { "Idigbo Planks", 80 },
    { "Indian Almond Planks", 81 },
    { "Indian Silver Greywood Planks", 82 },
    { "Izombe Planks", 83 },
    { "Jaboty Planks", 84 },
    { "Jagua Planks", 85 },
    { "Japanese Beech Planks", 86 },
    { "Japanese Birch Planks", 87 },
    { "Japanese Fir Planks", 88 },
    { "Japanese Hemlock Planks", 89 },
    { "Japanese Red Pine Planks", 90 },
    { "Japanese Spruce Planks", 91 },
    { "Jucaro Planks", 92 },
    { "Kaatoan Bangkal Planks", 93 },
    { "Kahikatea Planks", 94 },
    { "Kaki Planks", 95 },
    { "Katsura Planks", 96 },
    { "Kauvula Planks", 97 },
    { "Kirikawa (Marakaipo) Planks", 98 },
    { "Lampati Planks", 99 },
    { "Lancewood Planks", 100 },
    { "Larch (European) Planks", 101 },
    { "Lauro Preto Planks", 102 },
    { "Leche Perra Planks", 103 },
    { "Live Oak Planks", 104 },
    { "Long John Planks", 105 },
    { "Mango Planks", 106 },
    { "Mangrove Planks", 107 },
    { "Manwood Planks", 108 },
    { "Morototo Planks", 109 },
    { "Muhimbi Planks", 110 },
    { "Mulga Planks", 111 },
    { "Mutenye Planks", 112 },
    { "Nargusta Planks", 113 },
    { "New Guinea Boxwood Planks", 114 },
    { "Niangon Planks", 115 },
    { "Northern Catalpa Planks", 116 },
    { "Northern Sassafras Planks", 117 },
    { "Obota Planks", 118 },
    { "Odoko Planks", 119 },
    { "Ogea Planks", 120 },
    { "Okwen Planks", 121 },
    { "Oysterwood Planks", 122 },
    { "Pau Amarello Planks", 123 },
    { "Pawpap Planks", 124 },
    { "Pine (Radiata) Planks", 125 },
    { "Piqui Planks", 126 },
    { "Pochote Planks", 127 },
    { "Podo Planks", 128 },
    { "Poplar Gum Planks", 129 },
    { "Rauli Planks", 130 },
    { "Red Chacate Planks", 131 },
    { "Red Siris Planks", 132 },
    { "Red Spruce Planks", 133 },
    { "Red Tulip Oak Planks", 134 },
    { "Rengas Planks", 135 },
    { "Rose Alder Planks", 136 },
    { "Rubbertree (Rubberwood) Planks", 137 },
    { "Sajo Planks", 138 },
    { "Sapele Planks", 139 },
    { "Sapodilla Planks", 140 },
    { "Satine Planks", 141 },
    { "Scarlet Oak Planks", 142 },
    { "Sen Planks", 143 },
    { "Sepetir Planks", 144 },
    { "Serrette Planks", 145 },
    { "Siberian Yellow Pine Planks", 146 },
    { "Smooth-Leaved Elm Planks", 147 },
    { "Sophora Planks", 148 },
    { "Spruce Planks", 149 },
    { "Steamed Beech Planks", 150 },
    { "Subalpine Fir Planks", 151 },
    { "Sugi Planks", 152 },
    { "Swamp White Oak Planks", 153 },
    { "Sweet Birch Planks", 154 },
    { "Sycamore Planks", 155 },
    { "Table Mountain Pine Planks", 156 },
    { "Tamarind Planks", 157 },
    { "Taun Planks", 158 },
    { "Tawa Planks", 159 },
    { "Tchitola Planks", 160 },
    { "Tea Tree Planks", 161 },
    { "Timbauba Planks", 162 },
    { "Trumpetwood Planks", 163 },
    { "Verawood Planks", 164 },
    { "Wacapou Planks", 165 },
    { "Water Gum Planks", 166 },
    { "Water Tupelo Planks", 167 },
    { "West African Cordia Planks", 168 },
    { "White Cypress Pine Planks", 169 },
    { "White Hazelwood Planks", 170 },
    { "White Quangdong Planks", 171 },
    { "White-Topped Box Planks", 172 },
    { "Yellow Sanders Planks", 173 },
    { "Yellow Siris Planks", 174 },

    // HIGH
    { "Alder (European) Planks", 175 },
    { "Alder (Red) Planks", 176 },
    { "American Red Oak Planks", 177 },
    { "Apple Planks", 178 },
    { "Ash (European) Planks", 179 },
    { "Ayan Planks", 180 },
    { "Balsa Planks", 181 },
    { "Birch (European) Planks", 182 },
    { "Birch (Yellow) Planks", 183 },
    { "Cedar Planks", 184 },
    { "Cherry Planks", 185 },
    { "Cherry (European) Planks", 186 },
    { "Chestnut (Sweet) Planks", 187 },
    { "Elm (American) Planks", 188 },
    { "Elm (English) Planks", 189 },
    { "Elm European Planks", 190 },
    { "Green Oak Planks", 191 },
    { "Hickory Planks", 192 },
    { "Holly Planks", 193 },
    { "Iroko Planks", 194 },
    { "Lime, European Planks", 195 },
    { "Majau Planks", 196 },
    { "Maple (American) Planks", 197 },
    { "Oak - Joinery Grade S/E (Euro)", 198 },
    { "Oak - Prime S/E (Euro)", 199 },
    { "Obeche Planks", 200 },
    { "Pine (Eastern White) Planks", 201 },
    { "Pine (Lodgepole) Planks", 202 },
    { "Pine (Longleaf And Slash) Planks", 203 },
    { "Pine (Ponderosa) Planks", 204 },
    { "Pine (Sugar) Planks", 205 },
    { "Pine (Western White) Planks", 206 },
    { "Pine - Parana Pine Planks", 207 },
    { "Purpleheart Planks", 208 },
    { "Seasoned Oak Planks", 209 },
    { "Spruce (Sitka) Planks", 210 },
    { "Sycamore (European) Planks", 211 },
    { "Utile Planks", 212 },
    { "Willow Planks", 213 },
    { "Yew (European) Planks", 214 },
    { "Australian White Ash Planks", 215 },
    { "Light American Corda Planks", 216 },
    { "Nyatoh Planks", 217 },
    { "Oregon White Oak Planks", 218 },
    { "Paldao Planks", 219 },
    { "Palo Santo Planks", 220 },
    { "Red Lancewood Planks", 221 },
    { "Spanish Cedar Planks", 222 },

    // EXPENSIVE
    { "Accoya Planks", 223 },
    { "Afromosia Planks", 224 },
    { "Amboyna Planks", 225 },
    { "Anigre Planks", 226 },
    { "Aspen (Canadian) Planks", 227 },
    { "Basswood Planks", 228 },
    { "Black Walnut (American) Planks", 229 },
    { "Blackbean Planks", 230 },
    { "Boxwood (European) Planks", 231 },
    { "Cedar (Port Orford) Planks", 232 },
    { "Cedar (Southern White) Planks", 233 },
    { "Cedro Planks", 234 },
    { "Ceylon Satinwood Planks", 235 },
    { "Chestnut (American) Planks", 236 },
    { "Chestnut (Horse) Planks", 237 },
    { "Coachwood Planks", 238 },
    { "Cumaru Planks", 239 },
    { "Degame Planks", 240 },
    { "Dogwood Planks", 241 },
    { "Freijo Planks", 242 },
    { "Hackberry Planks", 243 },
    { "Imbuia Planks", 244 },
    { "Ipe Planks", 245 },
    { "Jelutong Planks", 246 },
    { "Kapur Planks", 247 },
    { "Koa Planks", 248 },
    { "Lati Planks", 249 },
    { "Light Virola Planks", 250 },
    { "Magnolia Planks", 251 },
    { "Mansonia Planks", 252 },
    { "Merbau Planks", 253 },
    { "Mesquite Planks", 254 },
    { "Muhuhu Planks", 255 },
    { "Muninga Planks", 256 },
    { "Myrtle Planks", 257 },
    { "Oak (American White) Planks", 258 },
    { "Oak - Character Grade (Euro)", 259 },
    { "Olive (East African) Planks", 260 },
    { "Olive (European) Planks", 261 },
    { "Opepe Planks", 262 },
    { "Padauk - African Planks", 263 },
    { "Paduak Planks", 264 },
    { "Panga Panga Planks", 265 },
    { "Paulownia Planks", 266 },
    { "Pear Planks", 267 },
    { "Pecan Planks", 268 },
    { "Pine (Hoop) Planks", 269 },
    { "Pine (Kauri) Planks", 270 },
    { "Primavera Planks", 271 },
    { "Quebracho Planks", 272 },
    { "Ramin Planks", 273 },
    { "Robinia Planks", 274 },
    { "Sassafras Planks", 275 },
    { "Sequoia (Redwood) Planks", 276 },
    { "Snakewood Planks", 277 },
    { "Sucupira Planks", 278 },
    { "Thermowood Planks", 279 },
    { "Yellow Buckeye Planks", 280 },
    { "Ziricote Planks", 281 },
    { "Acajou Rouge Planks", 282 },
    { "Amendoim Planks", 283 },
    { "Bishopwood Planks", 284 },
    { "Brush Box Planks", 285 },
    { "Cativo Planks", 286 },
    { "East Indian Kauri Planks", 287 },
    { "Fitzroy Cypress Planks", 288 },
    { "Flamewood Planks", 289 },
    { "Jequitiba Planks", 290 },
    { "Kempas Planks", 291 },
    { "Keyaki Planks", 292 },
    { "Marblewood Planks", 293 },
    { "Moabi Planks", 294 },
    { "Omu Planks", 295 },
    { "Tonka Planks", 296 },
    { "Ulmo Planks", 297 },
    { "Yellow Carabeen Planks", 298 },

    // VERY EXPENSIVE
    { "Abura", 299 },
    { "Afara", 300 },
    { "Afzelia", 301 },
    { "Agba", 302 },
    { "Angelin", 303 },
    { "Avodire", 304 },
    { "Balau", 305 },
    { "Blackwood (African)", 306 },
    { "Blackwood (Australian)", 307 },
    { "Brazilwood", 308 },
    { "Bubinga", 309 },
    { "Cerejeira", 310 },
    { "Cocobolo", 311 },
    { "Courbaril", 312 },
    { "Ebony (African)", 313 },
    { "Ebony (Macassar)", 314 },
    { "Ekki", 315 },
    { "Gaboon", 316 },
    { "Gedu Nohor", 317 },
    { "Goncalo Alves", 318 },
    { "Greenheart", 319 },
    { "Guanacaste", 320 },
    { "Guarea", 321 },
    { "Jacaranda Pardo", 322 },
    { "Jacareuba", 323 },
    { "Jarrah", 324 },
    { "Karri", 325 },
    { "Keruing", 326 },
    { "Kingwood", 327 },
    { "Kokko", 328 },
    { "Koto", 329 },
    { "Laburnum", 330 },
    { "Lignum Vitae", 331 },
    { "Madrona", 332 },
    { "Mahogany (American)", 333 },
    { "Mahogany - African", 334 },
    { "Makore", 335 },
    { "Maracaibo Boxwood", 336 },
    { "Massaranduba", 337 },
    { "Mengkulang", 338 },
    { "Mersawa", 339 },
    { "Okan", 340 },
    { "Osage-Orange", 341 },
    { "Ovangkol", 342 },
    { "Padauk (Burma)", 343 },
    { "Pau Marfim", 344 },
    { "Peroba Rosa", 345 },
    { "Persimmon", 346 },
    { "Rosewood (Brazilian)", 347 },
    { "Rosewood (Honduras)", 348 },
    { "Rosewood (Indian)", 349 },
    { "Sheoak", 350 },
    { "Tallowwood", 351 },
    { "Tatajuba", 352 },
    { "Teak", 353 },
    { "Teak (Rhodesian)", 354 },
    { "Walnut (African)", 355 },
    { "Wenge", 356 },
    { "Zebrano", 357 },
    { "Etimoe", 358 },
    { "Gabon Ebony", 359 },
    { "Miva Mahogany", 360 },
    { "Sandalwood", 361 },
    { "South American Walnut", 362 },
    { "Totara", 363 },
    { "Vanuatu Blackwood", 364 },
    };

    public enum resourceTypes
    {
        Wood, 
        Planks
    }

    public void UseResource(string resourceName, double amount)
    {
        if (_resourcesPlanks.ContainsKey(resourceName))
        {
            _resourcesPlanks[resourceName] -= amount;
            if (_resourcesPlanks[resourceName] < 0)
            {
                _resourcesPlanks[resourceName] = 0; // Prevent negative values
            }
        }
        else
        {
            GD.Print($"Resource '{resourceName}' not found in the dictionary.");
        }
    }

    public void CraftPlanks(string resourceName, double amount)
    {
        if (_resourcesPlanks.ContainsKey(resourceName))
        {
            double cost = _resourcesPlankCraftCost[resourceName] * amount;
            if (_resourcesWood[resourceName] >= cost)
            {
                _resourcesPlanks[resourceName] += amount;
                UseResource(resourceName, cost);
                GD.Print($"Crafted {amount} planks from {resourceName}. Cost: {cost}");
            }
            else
            {
                GD.Print($"Not enough {resourceName} to craft {amount} planks. Required: {cost}, Available: {_resourcesPlanks[resourceName]}");
            }
        }
        else
        {
            GD.Print($"Resource '{resourceName}' not found in the dictionary.");
        }
    }

    /// <summary>
    /// Get the amount of specified resource. Returns 0 if the resource is not found.
    /// </summary>
    /// <param name="resourceName"></param>
    /// <returns></returns>
    public double GetResourceAmount(string resourceName)
    {
        if (_resourcesPlanks.ContainsKey(resourceName))
        {
            return _resourcesPlanks[resourceName];
        }
        else
        {
            GD.Print($"Resource '{resourceName}' not found in the dictionary.");
            return 0;
        }
    }

    /// <summary>
    /// Adds a specified amount to the resource. CHEATING CHEATING
    /// </summary>
    public void AddResource(string resourceName, double amount, resourceTypes type)
    {
        switch (type)
        {
            case resourceTypes.Planks:
            if (_resourcesPlanks.ContainsKey(resourceName))
            {
                _resourcesPlanks[resourceName] += amount;
            }
            break;
            case resourceTypes.Wood:
            if (_resourcesWood.ContainsKey(resourceName))
            {
                _resourcesWood[resourceName] += amount;
            }
            break;
        }
    }

    public void writeResouceDataToDB()
    {
        

        DatabaseManager _db = GetNode<DatabaseManager>("/root/DatabaseManager");
        foreach (var woodcount in _resourcesWood)
        {
            string sqlstring = @"UPDATE resources
            SET wood_count = @wood_count
            WHERE name = @name";
            Dictionary<string, object> param = new Dictionary<string, object>
            {
                {"@wood_count", _resourcesWood[woodcount.Key]},
                {"@name", woodcount.Key}
            };
            _db.WriteToDatabase(sqlstring, param);
        }
    }


/// <summary>
/// Inserts all the woods into the database as well as some basic info about them
/// </summary>
    public void AddWoodsToDataBase()
    {
        
        DatabaseManager _db = GetNode<DatabaseManager>("/root/DatabaseManager");
        int i = 0;
        float sellPrice = 0;
        foreach (var resource in _resourcesWood)
        {
            i++;
            sellPrice = CalculateWoodSellPrice(i);
            string sqlstring = @"INSERT OR IGNORE INTO resources (name, wood_count, plank_count, plank_craft_cost, wood_sell_price) 
            VALUES (@name, @wood_count, @plank_count, @plank_craft_cost, @wood_sell_price);";
            Dictionary<string, Object> param = new Dictionary<string, object>
            {
                    {"@name", resource.Key}, 
                    {"@wood_count", 0},
                    {"@plank_count", 0},
                    {"@plank_craft_cost", i},
                    {"@wood_sell_price", sellPrice} 
            };
            _db.WriteToDatabase(sqlstring, param);
        }
    }


    private float CalculateWoodSellPrice(int resourceId)
    {
        float sellPrice;
        sellPrice = 0.05f + (0.02f + 0.01f * resourceId); // Base price + incremental price based on resource ID
        return sellPrice;
    }

}
